name: much_todo
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.1.1+3

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  currency_text_input_formatter: ^2.1.10
  uuid: ^3.0.6
  shared_preferences: ^2.2.0
  firebase_core: ^2.15.0
  image_picker: ^1.0.1
  url_launcher: ^6.1.12
  auto_size_text: ^3.0.0
  photo_view: ^0.14.0
  provider: ^6.0.5
  syncfusion_flutter_sliders: ^22.2.7
  flutter_svg: ^2.0.7
  package_info_plus: ^4.1.0
  firebase_auth: ^4.7.3
  google_sign_in: ^6.1.4
  skeletonizer: ^0.7.0
  http: ^1.1.0
  firebase_crashlytics: ^3.3.5
  firebase_storage: ^11.2.6
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
