// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv_RLpcokqJrVfe1nxQIrMozFtbCf-SGg',
    appId: '1:895180784965:web:505b8f8d594252ddce2a2c',
    messagingSenderId: '895180784965',
    projectId: 'muchtodo-42777',
    authDomain: 'muchtodo-42777.firebaseapp.com',
    storageBucket: 'muchtodo-42777.appspot.com',
    measurementId: 'G-H6RC4J84W7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuyv07ZuYa6BsuZb7lEaEhKuqR8ALs-4c',
    appId: '1:895180784965:android:cbe4630666c34982ce2a2c',
    messagingSenderId: '895180784965',
    projectId: 'muchtodo-42777',
    storageBucket: 'muchtodo-42777.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPSutuUBv4tx1ptR7CT9ETTqPVl-uSGHg',
    appId: '1:895180784965:ios:cf8a7babf4a71e89ce2a2c',
    messagingSenderId: '895180784965',
    projectId: 'muchtodo-42777',
    storageBucket: 'muchtodo-42777.appspot.com',
    androidClientId: '895180784965-be01i6092tau233il28bkdj0qo68p4h4.apps.googleusercontent.com',
    iosClientId: '895180784965-rmtoaotd4no9duv7gau0i1umusn378pa.apps.googleusercontent.com',
    iosBundleId: 'com.joshrap.muchtodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPSutuUBv4tx1ptR7CT9ETTqPVl-uSGHg',
    appId: '1:895180784965:ios:d007ef720f3e7fd7ce2a2c',
    messagingSenderId: '895180784965',
    projectId: 'muchtodo-42777',
    storageBucket: 'muchtodo-42777.appspot.com',
    androidClientId: '895180784965-be01i6092tau233il28bkdj0qo68p4h4.apps.googleusercontent.com',
    iosClientId: '895180784965-tiq78sddc6jchvoj5fhojfu0p805fghr.apps.googleusercontent.com',
    iosBundleId: 'com.joshrap.muchtodo.RunnerTests',
  );
}
