// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv_RLpcokqJrVfe1nxQIrMozFtbCf-SGg',
    appId: '1:895180784965:web:505b8f8d594252ddce2a2c',
    messagingSenderId: '895180784965',
    projectId: 'muchtodo-42777',
    authDomain: 'muchtodo-42777.firebaseapp.com',
    storageBucket: 'muchtodo-42777.appspot.com',
    measurementId: 'G-H6RC4J84W7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuyv07ZuYa6BsuZb7lEaEhKuqR8ALs-4c',
    appId: '1:895180784965:android:b6109032242ee75dce2a2c',
    messagingSenderId: '895180784965',
    projectId: 'muchtodo-42777',
    storageBucket: 'muchtodo-42777.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPSutuUBv4tx1ptR7CT9ETTqPVl-uSGHg',
    appId: '1:895180784965:ios:21d81b1514dd44d3ce2a2c',
    messagingSenderId: '895180784965',
    projectId: 'muchtodo-42777',
    storageBucket: 'muchtodo-42777.appspot.com',
    iosClientId: '895180784965-e3i8a8keoo469udo0r9rr2dr4k41qa22.apps.googleusercontent.com',
    iosBundleId: 'com.joshrap.muchtodo.muchTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPSutuUBv4tx1ptR7CT9ETTqPVl-uSGHg',
    appId: '1:895180784965:ios:f1896332438696a4ce2a2c',
    messagingSenderId: '895180784965',
    projectId: 'muchtodo-42777',
    storageBucket: 'muchtodo-42777.appspot.com',
    iosClientId: '895180784965-2t3q2pbuv67d319j150b4od2t829l3b3.apps.googleusercontent.com',
    iosBundleId: 'com.joshrap.muchtodo.muchTodo.RunnerTests',
  );
}
